
onlyBuiltDependencies:
  - supabase
  - '@scarf/scarf'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - yarn

packages:
  - workers/*
  - packages/*

catalog:
  typescript: ^5.9.2
  wrangler: ^4.28.1