packages:
  - workers/*
  - packages/*

catalog:
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8
  typescript: ^5.9.2
  typescript-eslint: ^8.39.0
  wrangler: ^4.28.1

onlyBuiltDependencies:
  - '@scarf/scarf'
  - esbuild
  - msw
  - sharp
  - supabase
  - unrs-resolver
  - workerd
  - yarn
