
onlyBuiltDependencies:
  - supabase
  - '@scarf/scarf'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - yarn

packages:
  - workers/*
  - packages/*

catalog:
  typescript: ^5.9.2
  wrangler: ^4.28.1
  typescript-eslint: ^8.39.0
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8